main: com.admincmd.Main
name: ${project.name}
version: ${project.version}
authors: [TheJeterLP, JKMalan, Balor]
description: This plugin implements the basic commands for running a server.
softdepend: [ProtocolLib, Vault, MultiVerse, Multiverse-Core, Multiworld]
api-version: 1.13
