# This is a basic workflow to help you get started with Actions

name: Create main release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    if: "startsWith(github.event.commits[0].message, 'v')"
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install
      - name: Archive jar
        run: mkdir staging && cp target/*.jar staging
      - name: upload jar
        uses: actions/upload-artifact@v1
        with:
          name: AdminCMD ${{ github.event.commits[0].message }}  
          path: staging       
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.commits[0].message }}  
          release_name: AdminCMD ${{ github.event.commits[0].message }}  
          body: ${{ github.event.commits[0].message }}  
          draft: false
          prerelease: false
      - name: ZIP
        run: zip AdminCMD staging/*.jar
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./AdminCMD.zip
          asset_name: AdminCMD.zip
          asset_content_type: application/zip
  main:
    if: "!startsWith(github.event.commits[0].message, 'v')"
    name: Create Dev Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven Packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean install
    - name: Archive jar
      run: mkdir staging && cp target/*.jar staging
    - name: upload jar
      uses: actions/upload-artifact@v1
      with:
        name: ChatEx-DEVELOPMENT-BUILD
        path: staging  
      
